name: Publish to Nuget.org
description: "Publish nugets to Nuget.org"
inputs:
  NugetsPath:
    description: "Nugets path to publish to Nuget.org"
    required: true
  Token:
    description: "Nuget.org token"
    required: true
runs:
  using: composite
  steps:
    - name: Publish NuGet
      shell: pwsh
      env:
        token: ${{ inputs.Token }}
      run: |
        cd ${{ inputs.NugetsPath }}
        ls *.nupkg
        dotnet nuget push "**/*.nupkg" --skip-duplicate --no-symbols -k "$env:token" -s https://api.nuget.org/v3/index.json
